services:
  - type: web
    name: call-tracker-pro
    env: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
    # Auto-deploy on GitHub push
    autoDeploy: true